### ISSUE TITLE
Trouble with javascript console login

### ISSUE THREAD

**Issue by faddat** [Caerostris/Tier2#1]
Screenshots because I don't really know javascript 

[edit: screenshot removed]

but that is right, right?  I mean, I sure think it's right.  Thanks a bunch.  After I entered the token I get a 404 despite this mystery:

[edit: screenshot removed]

As in:  The API redirect thing you've got going seems to be up and working fine, but I'm still having issues nonetheless.  I'm just going to try replacing /html briefly and see if by some chance I misconfigured.... ???!!!!

Got the SSL cert in place as you requested.....

**Comment by faddat** [comment]
Tried firefox for good measure.  Generally, if I click "networks" then I get a 404, but usually when I get to the page itself (index.html) I get a 401.  Probably I'm doing something hilariously noobish.  Thanks for your help!

**Comment by Caerostris** [comment]
I took the liberty to remove the screenshots from your comment, as they showed your authentication secret. Please consider resetting your authentication token if you have anything actually running via that network controller.
According to the screenshots, your server is running ZeroTier version 1.1.4. I am not aware of any recent changes ZT has made to their API, but my test machine is still running 1.1.0.
I will update that machine tomorrow and see if I can replicate your situation.

**Comment by faddat** [comment]
aha, and thank you!  If there's anything that a non-javascripter can do to help out with Tier2, don't hesitate to ask.  

I'll freshen up that key, too :).  

-Jake

**Comment by Caerostris** [comment]
Managed to reproduce it.
It's not a bug in Tier2.
You need to compile ZeroTierOne with network controller support in order to run it as a network controller.
In order to update your installation, do the following:
- If you are actually using the network, make a backup of /var/lib/zerotier-one.
- Run `service zerotier-cli stop` to stop zerotier-one, make sure that zerotier-one is not running any more (if you run `zerotier-cli info` it should say `0 info connection failed`)
- Re-compile ZeroTierOne with network controller support: `mkdir ~/build && git clone https://github.com/ZeroTier/ZeroTierOne.git` to clone the ZeroTierOne source code, `make ZT_ENABLE_NETWORK_CONTROLLER=1` to compile ZT1 with network controller support, and `make ZT_ENABLE_NETWORK_CONTROLLER=1 installer` to build the installer package. Install the generated package.
- Start ZT1 and update the auth_secret in the Tier2 webinterface

**Comment by faddat** [comment]
Thanks a million for taking the time to reproduce my stupid oversight.  Seriously, much appreciated :100: .

You couldn't have made that any easier for me, you win kickass dev of the month!  Or whatever valorious honor could be given for going above & beyond...

Want a scaleway server? Let me know if you do, gladly launch one for you as a token of good cheer.

**Comment by Caerostris** [comment]
No worries at all Jake, you're welcome!
Haven't heard of scaleway yet, I'll look into it.
Glad I could help you out :)

**Comment by Caerostris** [comment]
I updated the Readme to make clear that network controller support is required.
Managed to reproduce your problem because I also forgot to add the option while upgrading my own installation...
